image: gitpod/workspace-python-3.8

tasks:
  - init: poetry shell && poetry install

vscode:
  extensions:
    - https://github.com/freeCodeCamp/freecodecamp-dark-vscode-theme/releases/download/v1.0.0/freecodecamp-dark-vscode-theme-1.0.0.vsix
